In [38]:
message = 'Hello Python'

for ch in message:
    print(ch)

H
e
l
l
o
 
P
y
t
h
o
n


In [39]:
fruit = ["orange","melon","lemon"]
for f in fruit:
    print(f)

orange
melon
lemon


In [40]:
import numpy as np

# n次元の単位行列を生成する関数
def create_identity_matrix(n):
    return np.eye(3)

identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
import numpy as np
import sympy
from sympy import Matrix, Symbol

a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
d = Symbol('d')
e = Symbol('e')
f = Symbol('f')
g = Symbol('g')
h = Symbol('h')
i = Symbol('i')
j = Symbol('j')
k = Symbol('k')
l = Symbol('l')
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

R = Matrix([[a, b, c], [d, e, f], [g, h, i]])
v = Matrix([[j], [k], [l]])
T = Matrix([[0, -z, y], [z, 0, -x], [-y, x, 0]])
h = R*v
n = T**(2)

print(h)
print(n)

Matrix([[a*j + b*k + c*l], [d*j + e*k + f*l], [g*j + h*k + i*l]])
Matrix([[-y**2 - z**2, x*y, x*z], [x*y, -x**2 - z**2, y*z], [x*z, y*z, -x**2 - y**2]])
