### This NoteBook provides some Notes about PyTorch Fundamental

In [1]:
import numpy as np
import torch
import torch.nn as nn
from torchvision import datasets

In [2]:
## check cuda（CUDAが利用可能かどうかを確認し、利用可能なら'cuda'を、それ以外なら'cpu'をデバイスとして選択）
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [3]:
## from numpy to tensor and from tensor to numpy
a = np.array([[1,2,3,4],[5,6,7,8]])
b = torch.from_numpy(a)
print(b)
c = b.numpy()
print(c)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
## device and requires_grad parameters（使用するデバイスを決定（'cuda'か'cpu'かを確認））
my_device = ('cuda' if torch.cuda.is_available() else 'cpu')
# 指定したデバイス上に、勾配計算が有効な5つの要素からなるテンソルを作成
x = torch.ones(5, device=device, requires_grad=True)    
## requires_grad（勾配の要求？） ----> calculate gradients for optimization（最適化のための勾配を計算する）
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

`Calculate the gradients with Autograd`

In [5]:
## Calculate gradients with Autograd（ランダムな3つの要素を持つテンソルを作成し、勾配計算を有効にする）
x = torch.randn(3, requires_grad=True)
print('x --> \n', x)

y = x + 2
print('y --> \n', y)

z = y * y * 2
z = z.mean()
print('z --> \n', z)

z.backward()  ## dz/dx

## get the graients
print('gradient --> \n', x.grad)

x --> 
 tensor([ 0.2244,  0.5929, -1.3174], requires_grad=True)
y --> 
 tensor([2.2244, 2.5929, 0.6826], grad_fn=<AddBackward0>)
z --> 
 tensor(8.0914, grad_fn=<MeanBackward0>)
gradient --> 
 tensor([2.9659, 3.4572, 0.9101])


In [6]:
# 0から6までの整数を持つ5x5のテンソルを作成し、勾配計算を有効にする
x = torch.randint(low=0, high=7, size=(5,5), dtype=torch.float32, requires_grad=True)
print('x --> \n', x)

y = x**2 + 5
print('y --> \n', y)

z = y.mean()
print('z --> \n', z)

z.backward() ## dz/dx

## get the graients
print('gradient --> \n', x.grad)

x --> 
 tensor([[0., 5., 3., 0., 6.],
        [3., 5., 4., 4., 5.],
        [1., 2., 4., 0., 5.],
        [0., 1., 1., 2., 4.],
        [2., 3., 5., 2., 3.]], requires_grad=True)
y --> 
 tensor([[ 5., 30., 14.,  5., 41.],
        [14., 30., 21., 21., 30.],
        [ 6.,  9., 21.,  5., 30.],
        [ 5.,  6.,  6.,  9., 21.],
        [ 9., 14., 30.,  9., 14.]], grad_fn=<AddBackward0>)
z --> 
 tensor(16.2000, grad_fn=<MeanBackward0>)
gradient --> 
 tensor([[0.0000, 0.4000, 0.2400, 0.0000, 0.4800],
        [0.2400, 0.4000, 0.3200, 0.3200, 0.4000],
        [0.0800, 0.1600, 0.3200, 0.0000, 0.4000],
        [0.0000, 0.0800, 0.0800, 0.1600, 0.3200],
        [0.1600, 0.2400, 0.4000, 0.1600, 0.2400]])


#### Done!