In [256]:
import numpy as np

In [257]:
from sympy import symbols, Matrix, cos, sin, pi, solve

In [258]:
def R(t,p):
    R = np.array([[np.cos(np.radians(p)), -np.sin(np.radians(p))*np.cos(np.radians(t)), np.sin(np.radians(p))*np.sin(np.radians(t))], 
                [np.sin(np.radians(p)), np.cos(np.radians(p))*np.cos(np.radians(t)), -np.cos(np.radians(p))*np.sin(np.radians(t))],
                [0, np.sin(np.radians(t)), np.cos(np.radians(t))]])
    return R

Kxx = -8.572
Kyy = 1.146
Kzz = 0.0
Kyz = -8.830
Kzx = 0.0
Kxy = 0.0

K = np.array([[Kxx, Kxy, Kzx], [Kxy, Kyy ,Kyz], [Kzx, Kyz, Kzz]])

R2 = np.array([[np.cos(np.radians(-120)), np.sin(np.radians(-120)), 0], [np.sin(np.radians(-120)), np.cos(np.radians(-120)), 0], [0, 0, 1]])
R3 = np.array([[np.cos(np.radians(120)), np.sin(np.radians(120)), 0], [np.sin(np.radians(120)), np.cos(np.radians(120)), 0], [0, 0, 1]])

Kn2 = R2 @ K @ R2.T
Kn3 = R3 @ K @ R3.T
Knn2 = R(90,90) @ Kn2 @ R(90,90).T
Knn3 = R(90,90) @ Kn3 @ R(90,90).T

print(Kn2)
print(Kn3)
print(Knn2)
print(Knn3)

[[-1.2835     -3.21555232  7.64700432]
 [-3.21555232 -6.1425      4.415     ]
 [ 7.64700432  4.415       0.        ]]
[[-1.2835      3.21555232 -7.64700432]
 [ 3.21555232 -6.1425      4.415     ]
 [-7.64700432  4.415       0.        ]]
[[ 3.95806374e-16  7.64700432e+00  4.41500000e+00]
 [ 7.64700432e+00 -1.28350000e+00 -3.21555232e+00]
 [ 4.41500000e+00 -3.21555232e+00 -6.14250000e+00]]
[[-1.47716950e-15 -7.64700432e+00  4.41500000e+00]
 [-7.64700432e+00 -1.28350000e+00  3.21555232e+00]
 [ 4.41500000e+00  3.21555232e+00 -6.14250000e+00]]


In [259]:
n1 = 0.180
n2 = 0.673
n3 = -0.718

s1 = 1
s2 = 0
s3 = 0

s4 = 0 
s5 = 0.68382885
s6 = -0.72964245

s7 = 0 
s8 = -0.72964245
s9 = -0.68382885 

C = np.cos(np.radians(21.77))
S = np.sin(np.radians(21.77))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv1 = np.array([[s1], [s2], [s3]])
sv2 = np.array([[s4], [s5], [s6]])
sv3 = np.array([[s7], [s8], [s9]])

h1 = T @ sv1
h2 = T @ sv2
h3 = T @ sv3

print(h2)
print(h3)
print(h1)

[[ 0.01261111]
 [ 0.73100335]
 [-0.68234639]]
[[-0.36498542]
 [-0.63195583]
 [-0.68376517]]
[[ 0.93099091]
 [-0.25765332]
 [-0.25882072]]


In [260]:
n1 = 1
n2 = 0
n3 = 0

s1 = 0.8660254
s2 = -0.5
s3 = 0

s4 = 0.34191442 
s5 = 0.59221316
s6 = -0.72964245

s7 = -0.36482122 
s8 = -0.6318889
s9 = -0.68382885

C = np.cos(np.radians(180))
S = np.sin(np.radians(180))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv1 = np.array([[s1], [s2], [s3]])
sv2 = np.array([[s4], [s5], [s6]])
sv3 = np.array([[s7], [s8], [s9]])

h1 = T @ sv1
h2 = T @ sv2
h3 = T @ sv3

print(h2)
print(h3)
print(h1)

[[ 0.34191442]
 [-0.59221316]
 [ 0.72964245]]
[[-0.36482122]
 [ 0.6318889 ]
 [ 0.68382885]]
[[ 8.660254e-01]
 [ 5.000000e-01]
 [-6.123234e-17]]


In [261]:
n1 = 0.180
n2 = 0.673
n3 = -0.718

s1 = 0.8660254
s2 = -0.5
s3 = 0

s4 = 0.34191442 
s5 = 0.59221316
s6 = -0.72964245

s7 = -0.36482122 
s8 = -0.6318889
s9 = -0.68382885

C = np.cos(np.radians(180))
S = np.sin(np.radians(180))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv1 = np.array([[s1], [s2], [s3]])
sv2 = np.array([[s4], [s5], [s6]])
sv3 = np.array([[s7], [s8], [s9]])

h1 = T @ sv1
h2 = T @ sv2
h3 = T @ sv3

print(h2)
print(h3)
print(h1)

[[ 0.01232102]
 [ 0.73223379]
 [-0.68336336]]
[[0.36484284]
 [0.63196975]
 [0.6837426 ]]
[[-0.93104695]
 [ 0.25689163]
 [ 0.25936375]]


In [262]:
Kxx = -6.142
Kyy = -1.283
Kzz = 0.0
Kyz = 7.647
Kzx = 4.414
Kxy = 4.208

K = np.array([[Kxx, Kxy, Kzx], [Kxy, Kyy, Kyz], [Kzx, Kyz, Kzz]])

R2 = np.array([[np.cos(np.radians(-120)), np.sin(np.radians(-120)), 0], [np.sin(np.radians(-120)), np.cos(np.radians(-120)), 0], [0, 0, 1]])
R3 = np.array([[np.cos(np.radians(120)), np.sin(np.radians(120)), 0], [np.sin(np.radians(120)), np.cos(np.radians(120)), 0], [0, 0, 1]])

Kzz1 = K
Kzz2 = R2 @ K @ (R2.T)
Kzz3 = R3 @ K @ (R3.T)

print(Kzz1)
print(Kzz2)
print(Kzz3)

[[-6.142  4.208  4.414]
 [ 4.208 -1.283  7.647]
 [ 4.414  7.647  0.   ]]
[[ 1.1464849   0.99288069 -8.82949626]
 [ 0.99288069 -1.2830151  -7.64613613]
 [-8.82949626 -7.64613613  0.        ]]
[[-6.14198490e+00  7.42311931e+00  4.41549626e+00]
 [ 7.42311931e+00 -8.57148490e+00 -8.63867695e-04]
 [ 4.41549626e+00 -8.63867695e-04  0.00000000e+00]]


In [263]:
Kxx = -8.572
Kyy = 1.146
Kzz = 0.0
Kyz = 8.830
Kzx = 0.0
Kxy = 0.0

K = np.array([[Kxx, Kxy, Kzx], [Kxy, Kyy ,Kyz], [Kzx, Kyz, Kzz]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(K)

# Create a diagonal matrix with the eigenvalues
D = np.diag(eigenvalues)

# Print the diagonal matrix
print("Diagonal Matrix D:")
print(D)

# Display eigenvalues and their corresponding eigenvectors
for i in range(len(eigenvalues)):
    print(f"Eigenvalue: {eigenvalues[i]}")
    print(f"Corresponding Eigenvector: {eigenvectors[:, i]}")
    print()  # Add a blank line for better readability

Diagonal Matrix D:
[[-8.27557214  0.          0.        ]
 [ 0.          9.42157214  0.        ]
 [ 0.          0.         -8.572     ]]
Eigenvalue: -8.275572144702217
Corresponding Eigenvector: [ 0.          0.68382885 -0.72964245]

Eigenvalue: 9.421572144702218
Corresponding Eigenvector: [ 0.         -0.72964245 -0.68382885]

Eigenvalue: -8.572
Corresponding Eigenvector: [1. 0. 0.]



In [264]:
Kxx = -8.523
Kyy = 1.097
Kzz = 0.0
Kyz = -8.808
Kzx = 0.6218
Kxy = -0.6827

K = np.array([[Kxx, Kxy, Kzx], [Kxy, Kyy ,Kyz], [Kzx, Kyz, Kzz]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(K)

# Create a diagonal matrix with the eigenvalues
D = np.diag(eigenvalues)

# Print the diagonal matrix
print("Diagonal Matrix D:")
print(D)

# Display eigenvalues and their corresponding eigenvectors
for i in range(len(eigenvalues)):
    print(f"Eigenvalue: {eigenvalues[i]}")
    print(f"Corresponding Eigenvector: {eigenvectors[:, i]}")
    print()  # Add a blank line for better readability

Diagonal Matrix D:
[[ 9.42107105  0.          0.        ]
 [ 0.         -8.57120746  0.        ]
 [ 0.          0.         -8.27586358]]
Eigenvalue: 9.421071045696731
Corresponding Eigenvector: [ 0.05138714 -0.72781554  0.68384494]

Eigenvalue: -8.571207460869937
Corresponding Eigenvector: [-9.97497640e-01 -7.06991827e-02 -2.88683805e-04]

Eigenvalue: -8.275863584826789
Corresponding Eigenvector: [-0.04855739  0.68211888  0.72962731]



In [265]:
Kxx = -6.142
Kyy = -1.283
Kzz = 0.0
Kyz = 7.647
Kzx = 4.414
Kxy = 4.208

K = np.array([[Kxx, Kxy, Kzx], [Kxy, Kyy ,Kyz], [Kzx, Kyz, Kzz]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(K)

# Create a diagonal matrix with the eigenvalues
D = np.diag(eigenvalues)

# Print the diagonal matrix
print("Diagonal Matrix D:")
print(D)

# Display eigenvalues and their corresponding eigenvectors
for i in range(len(eigenvalues)):
    print(f"Eigenvalue: {eigenvalues[i]}")
    print(f"Corresponding Eigenvector: {eigenvectors[:, i]}")
    print()  # Add a blank line for better readability

Diagonal Matrix D:
[[ 9.42132764  0.          0.        ]
 [ 0.         -8.57148623  0.        ]
 [ 0.          0.         -8.27484141]]
Eigenvalue: 9.421327638480506
Corresponding Eigenvector: [-0.36479779 -0.63191468 -0.68381753]

Eigenvalue: -8.571486233067837
Corresponding Eigenvector: [-0.86531596  0.50122436 -0.00155843]

Eigenvalue: -8.274841405412674
Corresponding Eigenvector: [-0.3437308  -0.59114971  0.7296514 ]



In [266]:
# データ①の固有ベクトル
v1_1 = np.array([0, 0.68382885, -0.72964245])
v1_2 = np.array([0, -0.72964245, -0.68382885])
v1_3 = np.array([1, 0, 0])

# データ②の固有ベクトル
v2_1 = np.array([-0.04855739, 0.68211888, 0.72962731])
v2_2 = np.array([0.05138714, -0.72781554, 0.68384494])
v2_3 = np.array([-9.97497640e-01, -7.06991827e-02, -2.88683805e-04])

# ベクトルの正規化（単位ベクトルにする）
v1_1 = v1_1 / np.linalg.norm(v1_1)
v1_2 = v1_2 / np.linalg.norm(v1_2)
v1_3 = v1_3 / np.linalg.norm(v1_3)

v2_1 = v2_1 / np.linalg.norm(v2_1)
v2_2 = v2_2 / np.linalg.norm(v2_2)
v2_3 = v2_3 / np.linalg.norm(v2_3)

# 回転行列を求めるための関数
def rotation_matrix_from_vectors(vec1, vec2):
    """ Return the rotation matrix that aligns vec1 to vec2 """
    a, b = (vec1 / np.linalg.norm(vec1)).reshape(3), (vec2 / np.linalg.norm(vec2)).reshape(3)
    v = np.cross(a, b)  # 外積で回転軸を計算
    c = np.dot(a, b)    # 内積で回転角のコサインを計算
    s = np.linalg.norm(v)  # 外積のノルムが回転角のサインに対応
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s ** 2))
    return rotation_matrix, v / s  # 回転行列と正規化された回転軸を返す

# 各固有ベクトルの回転行列と回転軸を計算
R1, axis1 = rotation_matrix_from_vectors(v1_1, v2_1)
R2, axis2 = rotation_matrix_from_vectors(v1_2, v2_2)
R3, axis3 = rotation_matrix_from_vectors(v1_3, v2_3)

# 回転角を得るための関数
def rotation_angle_from_matrix(R):
    """ Return the rotation angle from the rotation matrix """
    angle = np.arccos((np.trace(R) - 1) / 2)
    return np.degrees(angle)

# 各回転行列から回転角を計算
angle1 = rotation_angle_from_matrix(R1)
angle2 = rotation_angle_from_matrix(R2)
angle3 = rotation_angle_from_matrix(R3)

# 結果を表示
print("Rotation axis for Eigenvalue -8.274:", axis1)
print("Rotation angle for Eigenvalue -8.274:", angle1)

print("Rotation axis for Eigenvalue 9.421:", axis2)
print("Rotation angle for Eigenvalue 9.421:", angle2)

print("Rotation axis for Eigenvalue -8.572:", axis3)
print("Rotation angle for Eigenvalue -8.572:", angle3)

Rotation axis for Eigenvalue -8.274: [0.99881524 0.03550675 0.03327731]
Rotation angle for Eigenvalue -8.274: 93.77936210585366
Rotation axis for Eigenvalue 9.421: [-0.99867347 -0.03521087  0.03756985]
Rotation angle for Eigenvalue 9.421: 86.36430835444159
Rotation axis for Eigenvalue -8.572: [ 0.          0.00408324 -0.99999166]
Rotation angle for Eigenvalue -8.572: 175.94581920869453


In [267]:
# データ①の固有ベクトル
v1_1 = np.array([0, 0.68382885, -0.72964245])
v1_2 = np.array([0, -0.72964245, -0.68382885])
v1_3 = np.array([1, 0, 0])

# データ②の固有ベクトル
v2_1 = np.array([-0.3437308, -0.59114971, 0.7296514])
v2_2 = np.array([-0.36479779, -0.63191468, -0.68381753])
v2_3 = np.array([-0.86531596, 0.50122436, -0.00155843])

# ベクトルの正規化（単位ベクトルにする）
v1_1 = v1_1 / np.linalg.norm(v1_1)
v1_2 = v1_2 / np.linalg.norm(v1_2)
v1_3 = v1_3 / np.linalg.norm(v1_3)

v2_1 = v2_1 / np.linalg.norm(v2_1)
v2_2 = v2_2 / np.linalg.norm(v2_2)
v2_3 = v2_3 / np.linalg.norm(v2_3)

# 回転行列を求めるための関数
def rotation_matrix_from_vectors(vec1, vec2):
    """ Return the rotation matrix that aligns vec1 to vec2 """
    a, b = (vec1 / np.linalg.norm(vec1)).reshape(3), (vec2 / np.linalg.norm(vec2)).reshape(3)
    v = np.cross(a, b)  # 外積で回転軸を計算
    c = np.dot(a, b)    # 内積で回転角のコサインを計算
    s = np.linalg.norm(v)  # 外積のノルムが回転角のサインに対応
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s ** 2))
    return rotation_matrix, v / s  # 回転行列と正規化された回転軸を返す

# 各固有ベクトルの回転行列と回転軸を計算
R1, axis1 = rotation_matrix_from_vectors(v1_1, v2_1)
R2, axis2 = rotation_matrix_from_vectors(v1_2, v2_2)
R3, axis3 = rotation_matrix_from_vectors(v1_3, v2_3)

# 回転角を得るための関数
def rotation_angle_from_matrix(R):
    """ Return the rotation angle from the rotation matrix """
    angle = np.arccos((np.trace(R) - 1) / 2)
    return np.degrees(angle)

# 各回転行列から回転角を計算
angle1 = rotation_angle_from_matrix(R1)
angle2 = rotation_angle_from_matrix(R2)
angle3 = rotation_angle_from_matrix(R3)

# 結果を表示
print("Rotation axis for Eigenvalue -8.274:", axis1)
print("Rotation angle for Eigenvalue 9.421:", angle1)

print("Rotation axis for Eigenvalue 9.421:", axis2)
print("Rotation angle for Eigenvalue 9.421:", angle2)

print("Rotation axis for Eigenvalue -8.572:", axis3)
print("Rotation angle for Eigenvalue -8.572:", angle3)

Rotation axis for Eigenvalue -8.274: [0.19304819 0.71591735 0.67096553]
Rotation angle for Eigenvalue 9.421: 159.4930753908228
Rotation axis for Eigenvalue 9.421: [ 0.18017451  0.67263776 -0.7177016 ]
Rotation angle for Eigenvalue 9.421: 21.76910698193047
Rotation axis for Eigenvalue -8.572: [-0.          0.00310923  0.99999517]
Rotation angle for Eigenvalue -8.572: 149.91880343459837


In [268]:
# データ①の固有ベクトル
v1_1 = np.array([0, 0.68382885, -0.72964245])
v1_2 = np.array([0, -0.72964245, -0.68382885])
v1_3 = np.array([1, 0, 0])

# データ②の固有ベクトル
v2_1 = np.array([0.72964245, 0.0, -0.68382885])
v2_2 = np.array([0.68382885, 0.0, 0.72964245])
v2_3 = np.array([0, -1, 0])

# ベクトルの正規化（単位ベクトルにする）
v1_1 = v1_1 / np.linalg.norm(v1_1)
v1_2 = v1_2 / np.linalg.norm(v1_2)
v1_3 = v1_3 / np.linalg.norm(v1_3)

v2_1 = v2_1 / np.linalg.norm(v2_1)
v2_2 = v2_2 / np.linalg.norm(v2_2)
v2_3 = v2_3 / np.linalg.norm(v2_3)

# 回転行列を求めるための関数
def rotation_matrix_from_vectors(vec1, vec2):
    """ Return the rotation matrix that aligns vec1 to vec2 """
    a, b = (vec1 / np.linalg.norm(vec1)).reshape(3), (vec2 / np.linalg.norm(vec2)).reshape(3)
    v = np.cross(a, b)  # 外積で回転軸を計算
    c = np.dot(a, b)    # 内積で回転角のコサインを計算
    s = np.linalg.norm(v)  # 外積のノルムが回転角のサインに対応
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s ** 2))
    return rotation_matrix, v / s  # 回転行列と正規化された回転軸を返す

# 各固有ベクトルの回転行列と回転軸を計算
R1, axis1 = rotation_matrix_from_vectors(v1_1, v2_1)
R2, axis2 = rotation_matrix_from_vectors(v1_2, v2_2)
R3, axis3 = rotation_matrix_from_vectors(v1_3, v2_3)

# 回転角を得るための関数
def rotation_angle_from_matrix(R):
    """ Return the rotation angle from the rotation matrix """
    angle = np.arccos((np.trace(R) - 1) / 2)
    return np.degrees(angle)

# 各回転行列から回転角を計算
angle1 = rotation_angle_from_matrix(R1)
angle2 = rotation_angle_from_matrix(R2)
angle3 = rotation_angle_from_matrix(R3)

# 結果を表示
print("Rotation axis for Eigenvalue -8.274:", axis1)
print("Rotation angle for Eigenvalue 9.421:", angle1)

print("Rotation axis for Eigenvalue 9.421:", axis2)
print("Rotation angle for Eigenvalue 9.421:", angle2)

print("Rotation axis for Eigenvalue -8.572:", axis3)
print("Rotation angle for Eigenvalue -8.572:", angle3)

Rotation axis for Eigenvalue -8.274: [-0.53958627 -0.6143081  -0.57573624]
Rotation angle for Eigenvalue 9.421: 60.06940633424332
Rotation axis for Eigenvalue 9.421: [-0.6143081  -0.53958627  0.57573624]
Rotation angle for Eigenvalue 9.421: 119.93059366575669
Rotation axis for Eigenvalue -8.572: [ 0.  0. -1.]
Rotation angle for Eigenvalue -8.572: 90.0


In [269]:
# 行列 A と B
A = np.array([[-8.572, 0.0, 0.0], [0.0, 1.146, 8.83], [0.0, 8.83, 0.0]])
B = np.array([[-8.523, -0.6827, 0.6218], [-0.6827, 1.0977, -8.808], [0.6218, -8.808, 0.0]])

# 行列 A の固有値と固有ベクトルを計算
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)

# 行列 B の固有値と固有ベクトルを計算
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)

# 行列 A の固有値と対応する固有ベクトルを表示
print("Eigenvalues and Eigenvectors of A:")
for i in range(len(eigenvalues_A)):
    print(f"Eigenvalue {i+1}: {eigenvalues_A[i]}")
    print(f"Corresponding Eigenvector {i+1}: {eigenvectors_A[:, i]}")
    print()

# 行列 B の固有値と対応する固有ベクトルを表示
print("Eigenvalues and Eigenvectors of B:")
for i in range(len(eigenvalues_B)):
    print(f"Eigenvalue {i+1}: {eigenvalues_B[i]}")
    print(f"Corresponding Eigenvector {i+1}: {eigenvectors_B[:, i]}")
    print()

# ユニタリ行列を計算
U = eigenvectors_B @ np.linalg.inv(eigenvectors_A)

print("Unitary matrix U:")
print(U)

# ユニタリ性の確認 (U U† = I であることを確認)
print("Check Unitarity (U @ U† should be identity):")
print(np.round(U @ U.conj().T, decimals=10))

Eigenvalues and Eigenvectors of A:
Eigenvalue 1: -8.275572144702217
Corresponding Eigenvector 1: [ 0.          0.68382885 -0.72964245]

Eigenvalue 2: 9.421572144702218
Corresponding Eigenvector 2: [ 0.         -0.72964245 -0.68382885]

Eigenvalue 3: -8.572
Corresponding Eigenvector 3: [1. 0. 0.]

Eigenvalues and Eigenvectors of B:
Eigenvalue 1: 9.421441853413409
Corresponding Eigenvector 1: [ 0.05138609 -0.72782907  0.68383061]

Eigenvalue 2: -8.571203965934066
Corresponding Eigenvector 2: [-9.97503280e-01 -7.06198476e-02 -2.06747794e-04]

Eigenvalue 3: -8.275537887479349
Corresponding Eigenvector 3: [-0.04844249  0.68211266  0.72964077]

Unitary matrix U:
[[-0.04844249  0.76296003  0.64462804]
 [ 0.68211266 -0.44618328  0.57934688]
 [ 0.72964077  0.46777395 -0.49881046]]
Check Unitarity (U @ U† should be identity):
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [270]:
# 行列 A と B
A = np.array([[-8.572, 0.0, 0.0], [0.0, 1.146, 8.83], [0.0, 8.83, 0.0]])
B = np.array([[-6.142, 4.208, 4.414], [4.208, -1.283, 7.647], [4.414, 7.647, 0.0]])

# 行列 A の固有値と固有ベクトルを計算
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)

# 行列 B の固有値と固有ベクトルを計算
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)

# 行列 A の固有値と対応する固有ベクトルを表示
print("Eigenvalues and Eigenvectors of A:")
for i in range(len(eigenvalues_A)):
    print(f"Eigenvalue {i+1}: {eigenvalues_A[i]}")
    print(f"Corresponding Eigenvector {i+1}: {eigenvectors_A[:, i]}")
    print()

# 行列 B の固有値と対応する固有ベクトルを表示
print("Eigenvalues and Eigenvectors of B:")
for i in range(len(eigenvalues_B)):
    print(f"Eigenvalue {i+1}: {eigenvalues_B[i]}")
    print(f"Corresponding Eigenvector {i+1}: {eigenvectors_B[:, i]}")
    print()

# ユニタリ行列を計算
U = eigenvectors_B @ np.linalg.inv(eigenvectors_A)

print("Unitary matrix U:")
print(U)

# ユニタリ性の確認 (U U† = I であることを確認)
print("Check Unitarity (U @ U† should be identity):")
print(np.round(U @ U.conj().T, decimals=10))

Eigenvalues and Eigenvectors of A:
Eigenvalue 1: -8.275572144702217
Corresponding Eigenvector 1: [ 0.          0.68382885 -0.72964245]

Eigenvalue 2: 9.421572144702218
Corresponding Eigenvector 2: [ 0.         -0.72964245 -0.68382885]

Eigenvalue 3: -8.572
Corresponding Eigenvector 3: [1. 0. 0.]

Eigenvalues and Eigenvectors of B:
Eigenvalue 1: 9.421327638480506
Corresponding Eigenvector 1: [-0.36479779 -0.63191468 -0.68381753]

Eigenvalue 2: -8.571486233067837
Corresponding Eigenvector 2: [-0.86531596  0.50122436 -0.00155843]

Eigenvalue 3: -8.274841405412674
Corresponding Eigenvector 3: [-0.3437308  -0.59114971  0.7296514 ]

Unitary matrix U:
[[-0.3437308   0.381912    0.85789997]
 [-0.59114971 -0.79783606  0.11832009]
 [ 0.7296514  -0.46647706  0.500008  ]]
Check Unitarity (U @ U† should be identity):
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]


In [271]:
na_a = np.array([0.0, 0.68382885, -0.72964245])
na_b = np.array([0.0, -0.72964245, -0.68382885])
na_c = np.array([1,0,0])
na_add = na_a + na_b + na_c
na_add

array([ 1.       , -0.0458136, -1.4134713])

In [272]:
na_a = np.array([0.05138714, -0.72781554, 0.683844943])
na_b = np.array([-9.97497640e-01, -7.06991827e-02, -2.88683805e-04])
na_c = np.array([-0.04855739, 0.68211888, 0.72962731])
na_add = na_a + na_b + na_c
na_add

array([-0.99466789, -0.11639584,  1.41318357])

In [273]:
na_a = np.array([-0.36479779, -0.63191468, -0.68381753])
na_b = np.array([-0.86531596, 0.50122436, -0.00155843])
na_c = np.array([-0.3437308, -0.59114971, 0.7296514])
na_add = na_a + na_b + na_c
na_add

array([-1.57384455, -0.72184003,  0.04427544])

In [274]:
# 2つのベクトルの定義
v1 = np.array([-0.99466789, -0.11639584,  1.41318357])
v2 = np.array([1.0, -0.0458136, -1.4134713])

# 回転軸の計算（外積）
axis = np.cross(v1, v2)
axis_normalized = axis / np.linalg.norm(axis)  # 単位ベクトルに正規化

# 回転角度の計算（内積からcosθを使って求める）
cos_theta = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
theta_rad = np.arccos(cos_theta)  # ラジアンでの角度
theta_deg = np.degrees(theta_rad)  # 度に変換

axis_normalized, theta_deg

(array([0.8164759 , 0.02581586, 0.57680208]), 174.62928218480488)

In [275]:
# Calculate cosine and sine of ? degrees
cos = np.cos(np.radians(12))
sin = np.sin(np.radians(12))
cos, sin

(0.9781476007338057, 0.20791169081775934)

In [276]:
n1,n2,n3 = 0,0,1
s1,s2,s3 = -0.36479779, -0.63191468, -0.68381753

t = 120

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[s1], [s2], [s3]])

h = T @ sv

print(h)

[[ 7.29653061e-01]
 [ 3.31866156e-05]
 [-6.83817530e-01]]


In [277]:
n1,n2,n3 = 0.8164759 , 0.02581586, 0.57680208

t = 174.62928218480488

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[-8.572, 0.0, 0.0], [0.0, 1.146, 8.83], [0.0, 8.83, 0.0]])

h = T @ sv @ T.T

print(h)

[[-1.15870465 -8.52947445 -1.77316393]
 [-8.52947445  1.87394889  1.97535696]
 [-1.77316393  1.97535696 -8.14124409]]


In [278]:
n1,n2,n3 = 0,0,1

t = 30

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[-6.142, 4.208, 4.414], [4.208, -1.283, 7.647], [4.414, 7.647, 0.0]])

h = T @ sv @ T.T

print(h)

[[-8.57148490e+00 -8.71849429e-06 -8.63867695e-04]
 [-8.71849429e-06  1.14648490e+00  8.82949626e+00]
 [-8.63867695e-04  8.82949626e+00  0.00000000e+00]]


In [279]:
n1,n2,n3 = 0,0,1

t = -90

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[-6.142, 4.208, 4.414], [4.208, -1.283, 7.647], [4.414, 7.647, 0.0]])

h = T @ sv @ T.T

print(h)

[[-1.283 -4.208  7.647]
 [-4.208 -6.142 -4.414]
 [ 7.647 -4.414  0.   ]]


In [280]:
n1,n2,n3 = 0,0,1

t = -64

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[-8.523, -0.6827, 0.6218], [-0.6827, 1.0977, -8.808], [0.6218, -8.808, 0.0]])

h = T @ sv @ T.T

print(h)

[[-1.28907776  4.21091962 -7.64399878]
 [ 4.21091962 -6.13622224 -4.4200432 ]
 [-7.64399878 -4.4200432   0.        ]]


In [281]:
n1,n2,n3 = 0,0,1

t = 30

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[-6.142, 4.208, 4.414], [4.208, -1.283, 7.647], [4.414, 7.647, 0.0]])

h = T @ sv @ T.T

print(h)

[[-8.57148490e+00 -8.71849429e-06 -8.63867695e-04]
 [-8.71849429e-06  1.14648490e+00  8.82949626e+00]
 [-8.63867695e-04  8.82949626e+00  0.00000000e+00]]


In [282]:
n1,n2,n3 = 0,0,1
s1,s2,s3 = -0.36479779, -0.63191468, -0.68381753
s4,s5,s6 = -0.86531596, 0.50122436, -0.00155843
s7,s8,s9 = -0.3437308, -0.59114971, 0.7296514

t = 30

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv1 = np.array([[s1], [s2], [s3]])
sv2 = np.array([[s4], [s5], [s6]])
sv3 = np.array([[s7], [s8], [s9]])

h1 = T @ sv1
h2 = T @ sv2
h3 = T @ sv3

print(h1)
print(h2)
print(h3)

[[ 3.31866156e-05]
 [-7.29653061e-01]
 [-6.83817530e-01]]
[[-0.99999778]
 [ 0.00141505]
 [-0.00155843]]
[[-0.00210475]
 [-0.68381607]
 [ 0.7296514 ]]


In [283]:
n1,n2,n3 = 0,0,1

t = 120

k1 = -1.2834932804107666
k2 = -6.142507076263428
k3 = -6.499399773929326e-07
k4 = -4.414998531341553
k5 = 7.647008419036865
k6 = -4.208017826080322

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[k1,k6,k5],[k6,k2,k4],[k5,k4,k3]])

h = T @ sv @ T.T

print(h)

[[-8.57200396e+00 -5.77923357e-06 -3.32370566e-06]
 [-5.77923357e-06  1.14600361e+00  8.83000282e+00]
 [-3.32370566e-06  8.83000282e+00 -6.49939977e-07]]


In [284]:
n1,n2,n3 = 0,0,1

t = 120

k1 = -6.142
k2 = -1.283
k3 = 0.0
k4 = 7.647
k5 = 4.414
k6 = 4.208

C = np.cos(np.radians(t))
S = np.sin(np.radians(t))

T = np.array([[n1**(2)*(1-C)+C, n1*n2*(1-C)-n3*S, n1*n3*(1-C)+n2*S], 
            [n1*n2*(1-C)+n3*S, n2**(2)*(1-C)+C, n2*n3*(1-C)-n1*S], 
            [n1*n3*(1-C)-n2*S, n2*n3*(1-C)+n1*S, n3**(2)*(1-C)+C]])

sv = np.array([[k1,k6,k5],[k6,k2,k4],[k5,k4,k3]])

h = T @ sv @ T.T

print(h)

[[ 1.14648490e+00  8.71849429e-06 -8.82949626e+00]
 [ 8.71849429e-06 -8.57148490e+00 -8.63867695e-04]
 [-8.82949626e+00 -8.63867695e-04  0.00000000e+00]]
